version: '3'

volumes:
  cache-pypoetry: {}

services:
  app:
    build: .
    volumes:
      - .:/app
      - cache-pypoetry:/root/.cache/pypoetry
    working_dir: /app
    ports:
      - "1111:5000"

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - '1112:8080'
    environment:
      URL: http://localhost:1111/swagger.json
